<a href="https://colab.research.google.com/github/Choigapju/NLP-study/blob/main/%EC%9E%90%EC%97%B0%EC%96%B4_%EA%B3%B5%EB%B6%80_RNN%20%ED%85%8D%EC%8A%A4%ED%8A%B8%20%EC%83%9D%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [ ]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]

print(np.shape(train_X))

(4, 5)


In [ ]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [ ]:
rnn = SimpleRNN(3)
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[0.8465809  0.9903875  0.35042366]], shape: (1, 3)


In [ ]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[0.8465809  0.9903875  0.35042366]], shape: (1, 3)


In [ ]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))


hidden states : [[[-0.69427866  0.38026226 -0.9885583 ]
  [-0.15734556 -0.7164579   0.7601514 ]
  [-0.6353941  -0.6050111  -0.8567509 ]
  [-0.9934629  -0.9477423  -0.05769924]]], shape: (1, 4, 3)
last hidden state : [[-0.9934629  -0.9477423  -0.05769924]], shape: (1, 3)


In [ ]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))


hidden state : [[ 0.99101967 -0.44755557  0.98695403]], shape: (1, 3)
last hidden state : [[ 0.99101967 -0.44755557  0.98695403]], shape: (1, 3)


In [ ]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))


hidden state : [[-0.5414294  -0.12832801 -0.00167134]], shape: (1, 3)
last hidden state : [[-0.5414294  -0.12832801 -0.00167134]], shape: (1, 3)
last cell state : [[-1.5656017  -0.21013646 -0.00710243]], shape: (1, 3)


In [ ]:
##LSTM 이해하기

In [ ]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [ ]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape: (1, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [ ]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)


In [ ]:
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [11]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [12]:
text = """경마장에 있는 말이 뛰고 있다\n
          그의 말이 법이다\n
          가는 말이 고와야 오는 말이 곱다\n"""

In [13]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' %vocab_size)

단어 집합의 크기 : 12


In [14]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [15]:
sequences = list()
for line in text.split('\n'):
  encoded = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)

print('학습에 사용할 샘플의 개수 : %d' %len(sequences))

학습에 사용할 샘플의 개수 : 11


In [16]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [17]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [18]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [19]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [20]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

In [21]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [22]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [23]:
y = to_categorical(y, num_classes=vocab_size)

In [24]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
## model design

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [27]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4937 - accuracy: 0.0909 - 1s/epoch - 1s/step
Epoch 2/200
1/1 - 0s - loss: 2.4817 - accuracy: 0.1818 - 8ms/epoch - 8ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4699 - accuracy: 0.0000e+00 - 7ms/epoch - 7ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4581 - accuracy: 0.0909 - 9ms/epoch - 9ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4462 - accuracy: 0.1818 - 8ms/epoch - 8ms/step
Epoch 6/200
1/1 - 0s - loss: 2.4342 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 7/200
1/1 - 0s - loss: 2.4219 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 8/200
1/1 - 0s - loss: 2.4092 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3960 - accuracy: 0.3636 - 7ms/epoch - 7ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3823 - accuracy: 0.3636 - 9ms/epoch - 9ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3678 - accuracy: 0.3636 - 6ms/epoch - 6ms/step
Epoch 12/200
1/1 - 0s - loss: 2.3526 - accuracy: 0.3636 - 8ms/epoch - 8ms/step
Epoch 13/200
1/1 - 0s - loss: 2.3366 - accuracy: 0.3636 - 8

In [28]:
def sentence_generation(model, tokenizer, current_word, n):
  init_word = current_word
  sentence = ''

  for i in range(n):
    encoded = tokenizer.texts_to_sequences([current_word])[0]
    encoded = pad_sequences([encoded], maxlen=5, padding='pre')
    result = model.predict(encoded, verbose=0)
    result = np.argmax(result, axis=1)

    for word, index in tokenizer.word_index.items():
      if index == result:
        break

    current_word = current_word + ' ' + word

  sentence = init_word + sentence
  return sentence

In [31]:
print(sentence_generation(model, tokenizer, '경마장에', 4))

경마장에


In [30]:
print(sentence_generation(model, tokenizer, '그의', 2))

그의


In [32]:
import pandas as pd
import numpy as np
from string import punctuation

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [34]:
df = pd.read_csv('ArticlesApril2017.csv')
df.head()

abstract                 articleID  articleWordCount  \
0      NaN  58def1347c459f24986d7c80               716   
1      NaN  58def3237c459f24986d7c84               823   
2      NaN  58def9f57c459f24986d7c90               575   
3      NaN  58defd317c459f24986d7c95              1374   
4      NaN  58df09b77c459f24986d7ca7               708   

                                byline documentType  \
0  By STEPHEN HILTNER and SUSAN LEHMAN      article   
1                      By GAIL COLLINS      article   
2               By THE EDITORIAL BOARD      article   
3                    By MICHAEL POWELL      article   
4                         By DEB AMLEN      article   

                                            headline  \
0  Finding an Expansive View  of a Forgotten Peop...   
1                  And Now,  the Dreaded Trump Curse   
2              Venezuela’s Descent Into Dictatorship   
3              Stain Permeates Basketball Blue Blood   
4                          Taking Things for Granted   

                                            keywords  multimedia    newDesk  \
0  ['Photography', 'New York Times', 'Niger', 'Fe...           3    Insider   
1  ['United States Politics and Government', 'Tru...           3       OpEd   
2  ['Venezuela', 'Politics and Government', 'Madu...           3  Editorial   
3  ['Basketball (College)', 'University of North ...           3     Sports   
4                              ['Crossword Puzzles']           3      Games   

   printPage              pubDate         sectionName  \
0          2  2017-04-01 00:15:41             Unknown   
1         23  2017-04-01 00:23:58             Unknown   
2         22  2017-04-01 00:53:06             Unknown   
3          1  2017-04-01 01:06:52  College Basketball   
4          0  2017-04-01 02:00:14             Unknown   

                                             snippet              source  \
0  One of the largest photo displays in Times his...  The New York Times   
1                  Meet the gang from under the bus.  The New York Times   
2  A court ruling annulling the legislature’s aut...  The New York Times   
3  For two decades, until 2013, North Carolina en...  The New York Times   
4  In which Howard Barkin and Will Shortz teach u...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2017/03/31/insider/nig...  
1          Op-Ed  https://www.nytimes.com/2017/03/31/opinion/and...  
2      Editorial  https://www.nytimes.com/2017/03/31/opinion/ven...  
3           News  https://www.nytimes.com/2017/03/31/sports/ncaa...  
4           News  https://www.nytimes.com/2017/03/31/crosswords/...

In [35]:
print('열의 개수: ', len(df.columns))
print(df.columns)

열의 개수:  16
Index(['abstract', 'articleID', 'articleWordCount', 'byline', 'documentType',
       'headline', 'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [36]:
print(df['headline'].isnull().values.any())

False


In [37]:
headline = []

headline.extend(list(df.headline.values))
headline[:5]

['Finding an Expansive View  of a Forgotten People in Niger',
 'And Now,  the Dreaded Trump Curse',
 'Venezuela’s Descent Into Dictatorship',
 'Stain Permeates Basketball Blue Blood',
 'Taking Things for Granted']

In [38]:
print('총 샘플의 개수: {}'.format(len(headline)))

총 샘플의 개수: 886


In [41]:
headline = [word for word in headline if word != "Unknown"]
print('노이즈값 제거 후 샘플의 개수: {}'.format(len(headline)))

노이즈값 제거 후 샘플의 개수: 831


In [42]:
headline[:5]

['Finding an Expansive View  of a Forgotten People in Niger',
 'And Now,  the Dreaded Trump Curse',
 'Venezuela’s Descent Into Dictatorship',
 'Stain Permeates Basketball Blue Blood',
 'Taking Things for Granted']

In [44]:
from pandas.io.xml import preprocess_data
def repreprocessing(raw_sentence):
  preproceseed_sentence = raw_sentence.encode("utf8").decode("ascii", 'ignore')
  ## 구두점 제거와 소문자화
  return ''.join(word for word in preproceseed_sentence if word not in punctuation).lower()

preprocessed_headline = [repreprocessing(x) for x in headline]
preprocessed_headline[:5]

['finding an expansive view  of a forgotten people in niger',
 'and now  the dreaded trump curse',
 'venezuelas descent into dictatorship',
 'stain permeates basketball blue blood',
 'taking things for granted']

In [45]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_headline)
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 2422


In [46]:
sequences = list()

for sentence in preprocessed_headline:
  #각 샘플에 대한 정수 인코딩
  encoded = tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)

sequences[:11]

[[169, 17],
 [169, 17, 665],
 [169, 17, 665, 367],
 [169, 17, 665, 367, 4],
 [169, 17, 665, 367, 4, 2],
 [169, 17, 665, 367, 4, 2, 666],
 [169, 17, 665, 367, 4, 2, 666, 170],
 [169, 17, 665, 367, 4, 2, 666, 170, 5],
 [169, 17, 665, 367, 4, 2, 666, 170, 5, 667],
 [6, 80],
 [6, 80, 1]]

In [47]:
index_to_word = {}
for key, value in tokenizer.word_index.items():
  index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : exist


In [52]:
max_len = max(len(l) for l in sequences)
print('샘플 최대 길이 : {}'.format(max_len))

샘플 최대 길이 : 19


In [53]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169
   17]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17
  665]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17 665
  367]]


In [54]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [55]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17 665]]


In [56]:
print(y[:3])

[ 17 665 367]


In [57]:
y = to_categorical(y, num_classes=vocab_size)

In [58]:
#모델 설계

In [59]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [60]:
embedding_dim = 10
hidden_units = 128

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(LSTM(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
151/151 - 6s - loss: 7.4251 - accuracy: 0.0320 - 6s/epoch - 37ms/step
Epoch 2/200
151/151 - 4s - loss: 6.9131 - accuracy: 0.0312 - 4s/epoch - 25ms/step
Epoch 3/200
151/151 - 5s - loss: 6.7922 - accuracy: 0.0298 - 5s/epoch - 31ms/step
Epoch 4/200
151/151 - 5s - loss: 6.7068 - accuracy: 0.0304 - 5s/epoch - 35ms/step
Epoch 5/200
151/151 - 5s - loss: 6.6169 - accuracy: 0.0381 - 5s/epoch - 31ms/step
Epoch 6/200
151/151 - 4s - loss: 6.5096 - accuracy: 0.0483 - 4s/epoch - 26ms/step
Epoch 7/200
151/151 - 4s - loss: 6.3856 - accuracy: 0.0506 - 4s/epoch - 30ms/step
Epoch 8/200
151/151 - 5s - loss: 6.2645 - accuracy: 0.0497 - 5s/epoch - 31ms/step
Epoch 9/200
151/151 - 4s - loss: 6.1271 - accuracy: 0.0543 - 4s/epoch - 28ms/step
Epoch 10/200
151/151 - 5s - loss: 5.9871 - accuracy: 0.0593 - 5s/epoch - 31ms/step
Epoch 11/200
151/151 - 5s - loss: 5.8432 - accuracy: 0.0626 - 5s/epoch - 31ms/step
Epoch 12/200
151/151 - 5s - loss: 5.7075 - accuracy: 0.0641 - 5s/epoch - 33ms/step
Epoch 13/200


In [61]:
def sentence_generation(model, tokenizer, current_word, n):
  init_word = current_word
  sentence = ''

  for i in range(n):
    encoded = tokenizer.texts_to_sequences([current_word])[0]
    encoded = pad_sequences([encoded], maxlen=max_len-1, padding='pre')

    result = model.predict(encoded, verbose=0)
    result = np.argmax(result, axis=1)

    for word, index in tokenizer.word_index.items():
      if index == result:
        break
    
    current_word = current_word + ' ' + word

    sentence = sentence + ' ' + word

  sentence = init_word + sentence
  return sentence

In [62]:
print(sentence_generation(model, tokenizer, 'i', 10))

i love my sublet and i want to buy it how


In [63]:
print(sentence_generation(model, tokenizer, 'how', 10))

how to be mindful while cleaning the bathroom vote count to
